# SPRING
spring:
  data:
    mongodb:
      uri: mongodb://localhost/wallet

# SERVER PORT
server:
  port: 4000

# IDENTITY
keycloak:
  # `auth-server-url` must exactly match the issuer of the token
  auth-server-url: ${SERVICES_ACCOUNT_PUBLIC_URL:https://account.devied.com}${SERVICES_ACCOUNT_PATH:/auth}
  realm: ${SERVICES_ACCOUNT_REALM:devied}
  resource: ${SERVICES_ACCOUNT_CLIENT:wallet}
  bearer-only: ${SERVICES_ACCOUNT_BEARER:true}
  principal-attribute: ${SERVICES_ACCOUNT_PRINCIPAL_ATTRIBUTE:preferred_username}

# PAYPAL

paypal:
  clientId: "Your client ID"
  secret:  "Your secret"
  mode: sandbox
  cancelUrl: ${SERVICES_LIVE_PUBLIC_URL:https://live.test.com}/cancel
  returnUrl: ${SERVICES_LIVE_PUBLIC_URL:https://live.test.com}/check


# APP
app:
  api:
    allowed-origins:
      - ${SERVICES_LIVE_PUBLIC_URL:https://live.test.com}
  signaling:
    allowed-origins:
      - ${SERVICES_LIVE_PUBLIC_URL:https://live.test.com}

